In [2]:
import pandas as pd
import numpy as np
from datetime import date
import calendar
ozone2010=pd.read_csv("daily_avg_O3_2010.csv",sep=",", dtype=object)
ozone2010.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.498001,-87.881412,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,39,NaN,-,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",4/12/2016
1,1,3,10,44201,1,30.498001,-87.881412,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,31,NaN,-,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",4/12/2016
2,1,3,10,44201,1,30.498001,-87.881412,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,36,NaN,-,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",4/12/2016
3,1,3,10,44201,1,30.498001,-87.881412,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,40,NaN,-,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",4/12/2016
4,1,3,10,44201,1,30.498001,-87.881412,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,41,NaN,-,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",4/12/2016

In [4]:
ozone2010cal = ozone2010[(ozone2010['State Name'] == "California")]
ozone2010cal.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
23576,6,1,7,44201,1,37.687526,-121.784217,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,15,NaN,-,Livermore,793 Rincon Ave.,California,Alameda,Livermore,"San Francisco-Oakland-Hayward, CA",4/13/2016
23577,6,1,7,44201,1,37.687526,-121.784217,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,17,NaN,-,Livermore,793 Rincon Ave.,California,Alameda,Livermore,"San Francisco-Oakland-Hayward, CA",4/13/2016
23578,6,1,7,44201,1,37.687526,-121.784217,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,17,NaN,-,Livermore,793 Rincon Ave.,California,Alameda,Livermore,"San Francisco-Oakland-Hayward, CA",4/13/2016
23579,6,1,7,44201,1,37.687526,-121.784217,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,13,NaN,-,Livermore,793 Rincon Ave.,California,Alameda,Livermore,"San Francisco-Oakland-Hayward, CA",4/13/2016
23580,6,1,7,44201,1,37.687526,-121.784217,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,8,NaN,-,Livermore,793 Rincon Ave.,California,Alameda,Livermore,"San Francisco-Oakland-Hayward, CA",4/13/2016

In [ ]:
ozone2010 = ozone2010[(ozone2010['State Name'] == "California")]

#rename columns from excel2010data
ozone2010df=ozone2010.rename(columns={"Arithmetic Mean":"mean ozone", "1st Max Value":"max ozone"})
#blanks with underscores
ozone2010df.columns=[c.replace(" ", "_") for c in ozone2010df.columns]

#change date-time
ozone2010df["Date_Local"]=pd.to_datetime(ozone2010df["Date_Local"])

In [ ]:
#change date
#ozone2010[[""]]