In [4]:
import pandas as pd

In [5]:
# The path to our CSV file
file = "Resources/asthma-visits.csv"

# Read our Kickstarter data into pandas
df = pd.read_csv(file)
df.head()

,LGHC Indicator Name,Geography,Year,Age Group,Strata,Strata Name,Numerator,Rate,LGHC Indicator ID,LGHC Target Rate
0,Asthma ED Visit Rates,Alameda,2015,18 and Over,Total Population,18 and Over,"6,513",53.1,7,28
1,Asthma ED Visit Rates,Amador,2015,18 and Over,Total Population,18 and Over,151,49.1,7,28
2,Asthma ED Visit Rates,Butte,2015,18 and Over,Total Population,18 and Over,736,43.8,7,28
3,Asthma ED Visit Rates,Calaveras,2015,18 and Over,Total Population,18 and Over,139,42.7,7,28
4,Asthma ED Visit Rates,California,2015,18 and Over,Total Population,18 and Over,"117,854",40.0,7,28

In [6]:
year = df["Year"]

In [7]:
#rate = rate per 10,000 residents
gs = df.groupby(['Geography', year])['Rate'].mean().unstack()#.fillna(0)
gs

Year,2011,2012,2013,2014,2015,2016
Geography,,,,,,
Alameda,70.917391,79.173913,81.721739,128.500000,132.358333,79.700000
Amador,78.483333,87.500000,84.684615,66.728571,63.033333,71.020000
Butte,72.733333,70.563158,70.825000,80.825000,89.030000,68.961111
Calaveras,66.508333,45.266667,60.884615,61.607143,48.040000,50.427273
California,61.891667,65.045833,63.841667,66.741667,67.525000,64.079167
Colusa,38.978571,39.085714,52.925000,46.178571,48.160000,32.015385
Contra Costa,93.234783,95.360870,85.095455,87.113043,84.140909,78.377273
Del Norte,83.337500,84.746667,63.771429,64.833333,61.642857,85.978571
El Dorado,38.443750,72.529412,39.562500,52.550000,43.105882,39.205882
Fresno,81.352174,92.133333,89.590476,83.345455,95.057143,88.590909
Glenn,48.685714,39.400000,44.442857,44.946667,43.760000,39.173333
Humboldt,83.214286,91.400000,97.145000,98.150000,85.425000,116.457143
Humbolt,NaN,NaN,NaN,NaN,NaN,50.400000
Imperial,91.535294,125.038889,100.350000,95.056250,93.450000,93.861111
Inyo,64.407143,61.050000,62.866667,69.062500,58.585714,68.100000
Kern,70.671429,83.833333,80.880952,83.652381,81.833333,75.142857
Kings,115.705556,127.677778,113.827778,111.273684,114.022222,89.842105
Lake,133.758824,108.435294,95.061111,102.557895,97.194118,96.127778
Lassen,42.118182,39.925000,45.375000,46.076923,55.200000,52.375000
Los Angeles,62.304167,64.816667,64.704167,66.770833,65.408696,66.037500
Madera,112.500000,122.655556,91.016667,94.944444,103.194444,138.527778
Marin,49.320000,48.247619,44.490000,51.040000,35.460000,39.875000
Mariposa,51.954545,47.018182,46.910000,42.554545,54.010000,57.530000
Mendocino,116.326316,83.863158,63.916667,101.321053,71.929412,59.747059
Merced,118.945000,129.523810,127.104762,129.126316,126.080000,115.552381
Modoc,61.050000,68.133333,57.350000,80.600000,76.800000,88.880000
Mono,15.966667,17.860000,29.010000,30.537500,32.309091,31.228571
Monterey,61.433333,61.995000,69.470000,63.338095,71.461905,59.676190
Napa,44.194444,50.410526,47.494737,60.652632,48.700000,41.963158
Nevada,51.678571,46.180000,77.026667,42.385714,41.571429,33.707143
Orange,44.154545,50.285714,46.736364,49.527273,48.927273,47.623810
Placer,37.870000,40.352381,43.614286,46.628571,45.076190,49.947619
Plumas,63.366667,61.930000,65.041667,50.125000,78.464286,155.607692
Riverside,53.873913,55.382609,53.072727,53.508333,54.812500,57.300000
Sacramento,72.917391,77.591304,77.586957,82.475000,84.150000,76.662500
San Benito,65.500000,49.653333,64.600000,61.221429,56.960000,57.000000
San Bernardino,71.430435,77.743478,72.091304,69.052174,73.950000,86.354167
San Diego,49.869565,53.000000,49.682609,57.243478,47.460870,42.352174
San Francisco,70.113636,74.547826,69.768182,68.790476,67.195238,79.743478
San Joaquin,77.500000,79.876190,82.426087,82.636364,84.178261,81.371429
San Luis Obispo,51.552941,43.929412,39.341176,45.070588,48.705882,43.666667
San Mateo,49.738095,57.947826,44.519048,43.600000,42.923810,45.780952
Santa Barbara,47.084211,60.378947,58.180952,65.530000,60.133333,58.271429
Santa Clara,46.542857,45.176190,42.571429,42.980952,46.690476,43.519048
Santa Cruz,46.927778,46.823529,52.457895,58.135294,44.094118,40.237500
Shasta,85.044444,71.231579,88.121053,82.100000,63.976190,62.794737
Sierra,108.716667,NaN,92.450000,39.000000,40.300000,24.600000
Siskiyou,39.100000,70.953846,45.384615,74.392857,45.564286,38.490909
Solano,94.950000,97.866667,91.340909,100.804762,97.345455,97.913636
Sonoma,69.400000,63.118182,57.204545,65.691304,53.754545,58.386364
Stanislaus,81.304762,86.819048,95.938095,98.066667,92.957143,79.166667
Sutter,35.205263,28.370588,40.131579,51.900000,39.927778,50.657895
Tehama,56.293333,57.350000,49.680000,63.940000,61.860000,59.973333
Trinity,50.680000,70.987500,44.871429,75.355556,65.485714,54.000000
Tulare,67.895000,67.115000,70.409524,62.031818,60.840909,59.404762
Tuolumne,55.038462,60.200000,58.492308,52.314286,52.250000,48.028571
Ventura,51.095238,49.823810,50.942857,55.547619,55.766667,47.661905
Yolo,42.468421,63.170000,47.723810,63.910000,57.423810,59.415000
Yuba,48.764706,48.158824,56.883333,57.543750,54.277778,63.525000

In [8]:
gsc = gs.fillna(0)
gsc.count()

Year
2011    59
2012    59
2013    59
2014    59
2015    59
2016    59
dtype: int64

In [9]:
gsg = df.groupby(['Strata Name', year])['Rate'].mean().unstack()#.fillna(0)
gsg

Year,2011,2012,2013,2014,2015,2016
Strata Name,,,,,,
18 and Over,43.131034,43.375439,42.864912,43.145614,43.382456,39.228070
African-American,191.812844,205.564545,192.913636,198.738889,193.732710,207.680909
All Ages,50.755172,50.892982,50.194828,51.612281,51.771930,47.610526
American Indian/Alaskan Native,47.072414,63.648387,59.836364,91.030000,94.357143,83.638710
Asian/Pacific Islander,24.272500,23.616250,22.624096,25.180000,24.791765,28.515730
Female,57.911585,56.523313,56.797576,57.795152,57.349091,52.662264
Hispanic,48.992086,48.547482,48.628571,60.490972,44.583660,49.210345
Male,55.132530,56.555758,54.372561,56.412575,57.740719,54.729762
Under 18,73.758182,74.029091,71.446429,77.507273,77.454545,71.759649
White,56.998810,58.990419,55.608383,54.508982,54.140719,48.450000

In [119]:
df['Numerator'] = pd.to_numeric(df['Numerator'], errors='coerce')

gs2 = df.groupby(['Geography', year])['Numerator'].mean().unstack()#.fillna(0)
gs2

Year,2011,2012,2013,2014,2015,2016
Geography,,,,,,
Alameda,628.222222,496.400000,390.625000,326.285714,367.714286,356.714286
Amador,105.666667,112.142857,115.846154,102.461538,77.800000,73.066667
Butte,257.619048,245.304348,272.523810,273.238095,247.285714,226.900000
Calaveras,100.846154,72.642857,99.692308,86.571429,69.500000,76.384615
California,333.333333,358.000000,376.666667,474.000000,510.000000,448.000000
Colusa,25.733333,29.375000,31.200000,46.800000,39.333333,26.666667
Contra Costa,478.875000,339.555556,418.000000,363.181818,423.666667,457.200000
Del Norte,56.375000,48.588235,47.882353,45.647059,54.400000,53.157895
El Dorado,170.210526,178.368421,200.941176,173.631579,174.000000,151.047619
Fresno,235.900000,326.750000,253.000000,231.090909,277.700000,320.454545
Glenn,48.800000,41.333333,42.588235,42.933333,48.666667,39.733333
Humboldt,259.400000,245.083333,260.136364,253.956522,244.750000,217.227273
Humbolt,NaN,NaN,NaN,NaN,NaN,12.000000
Imperial,323.277778,413.529412,354.222222,384.600000,339.800000,329.375000
Inyo,32.111111,29.812500,32.250000,33.166667,29.555556,29.666667
Kern,467.600000,503.888889,445.000000,271.900000,328.125000,470.000000
Kings,337.421053,421.705882,395.058824,319.736842,337.684211,254.350000
Lake,115.150000,136.947368,124.380952,135.227273,137.000000,143.350000
Lassen,46.538462,42.071429,42.714286,48.928571,49.166667,48.642857
Los Angeles,180.500000,203.250000,190.250000,212.400000,193.000000,227.750000
Madera,320.647059,282.800000,248.100000,316.350000,297.111111,300.736842
Marin,214.761905,200.952381,192.952381,224.904762,155.285714,153.047619
Mariposa,32.666667,28.666667,31.000000,35.500000,41.857143,33.181818
Mendocino,153.476190,138.761905,146.263158,180.900000,202.421053,132.650000
Merced,391.850000,399.625000,394.937500,272.533333,283.857143,351.800000
Modoc,22.833333,26.400000,21.272727,29.454545,24.166667,25.538462
Mono,10.111111,11.444444,18.083333,19.428571,18.357143,13.428571
Monterey,426.526316,373.882353,337.176471,351.705882,343.800000,323.105263
Napa,164.380952,160.666667,157.428571,190.050000,172.150000,130.500000
Nevada,160.812500,157.066667,119.411765,138.625000,139.866667,112.642857
Orange,335.700000,369.857143,298.888889,372.777778,319.333333,398.444444
Placer,260.500000,273.050000,287.050000,270.250000,279.200000,272.761905
Plumas,34.733333,33.384615,41.000000,36.666667,35.941176,36.187500
Riverside,160.000000,267.875000,252.250000,276.444444,267.000000,269.875000
Sacramento,438.700000,398.000000,341.000000,381.777778,334.000000,380.000000
San Benito,107.882353,94.400000,124.666667,114.600000,119.466667,105.733333
San Bernardino,65.000000,69.333333,72.000000,61.857143,217.000000,216.428571
San Diego,266.857143,293.000000,377.625000,328.444444,360.750000,347.750000
San Francisco,437.133333,392.176471,435.263158,509.937500,491.833333,442.000000
San Joaquin,435.818182,390.300000,396.909091,350.833333,342.454545,409.166667
San Luis Obispo,275.888889,268.894737,239.421053,266.666667,299.421053,273.150000
San Mateo,407.625000,385.000000,367.937500,364.812500,386.466667,370.666667
Santa Barbara,332.950000,376.700000,372.666667,378.000000,421.000000,388.047619
Santa Clara,410.000000,454.000000,369.416667,397.333333,458.444444,461.700000
Santa Cruz,302.823529,264.095238,276.333333,280.550000,280.500000,268.631579
Shasta,252.434783,230.750000,264.750000,242.727273,219.217391,194.136364
Sierra,14.222222,5.000000,12.000000,44.400000,21.500000,11.666667
Siskiyou,51.375000,64.714286,57.222222,100.529412,98.111111,120.692308
Solano,361.375000,422.071429,386.235294,333.250000,403.800000,389.588235
Sonoma,320.588235,333.166667,278.722222,301.700000,334.631579,350.095238
Stanislaus,339.642857,305.000000,329.538462,287.230769,303.857143,321.076923
Sutter,91.352941,87.705882,83.700000,100.619048,96.523810,90.571429
Tehama,142.800000,107.333333,106.176471,112.625000,112.352941,102.210526
Trinity,25.307692,33.363636,26.444444,44.125000,39.000000,29.200000
Tulare,311.562500,309.812500,279.888889,248.666667,246.411765,335.950000
Tuolumne,80.941176,105.600000,101.333333,90.785714,90.235294,88.400000
Ventura,358.846154,357.923077,356.307692,355.142857,346.083333,380.571429
Yolo,198.380952,224.285714,209.904762,203.409091,247.904762,215.619048
Yuba,88.857143,88.368421,110.611111,91.368421,98.523810,87.850000