In [4]:
#import dependencies
import pandas as pd
import requests as req
#create separate file with individual log in credentials to be imported
from climatekeys import (user_id_aqs, password_aqs)
import csv
import time

In [5]:
#parameter codes
state_code = '06'
county_code = '001'
county_list = ["{0:03}".format(i) for i in range(116) if i%2 != 0]
#begin_date = '20110101'
#end_date =  '20111231'
years_list = ['2015']
parameter_code = '62101'

In [6]:
frames = []
header = ['Latitude', 'Longitude', 'Datum', 'Horizontal Accuracy', 'State Code',
       'County Code', 'Site Num', 'Parameter Code', 'POC',
       'AQS Parameter Desc', 'Date Local', '24 Hour Local', 'Date GMT',
       '24 Hour GMT', 'Year GMT', 'Day In Year GMT', 'Sample Measurement',
       'Units of Measure', 'Sample Duration', 'Sample Frequency',
       'Detection Limit', 'Measurement Uncertainty', 'Qualifier Description',
       'Method Type', 'Method Description']
missing = []

for year in years_list:
    for county_code in county_list:
        url = f"https://aqs.epa.gov/api/rawData?user={user_id_aqs}&pw={password_aqs}&format=DMCSV&param={parameter_code}&bdate={year}0101&edate={year}1231&state={state_code}&county={county_code}"
        response = req.get(url)
    
        if response.status_code == 200:
            
            print(f"succesfully requested for year:{year}, county:{county_code}")
            
            empty_list = []
            wrapper = csv.reader(response.text.strip().split('\n'))
            next(wrapper)   
            for record in wrapper:
                    
                empty_list.append(record) 
            try:  
                df = pd.DataFrame(empty_list, columns = header)
                frames.append(df)
                print(f"Added {len(df)} rows")
            except AssertionError:
                print(f"Empty")
                missing.append([year,county_code])
                
            

master_df = pd.concat(frames)
print(f"This is the length of the compiled DataFrame: {len(master_df}")
#print missing data: (year, county)
print(f"There are {len(missing)} missing counties")
print("Here are the missing years and counties")
print(missing)

succesfully requested for year:2015, county:001
Empty
succesfully requested for year:2015, county:003
Empty
succesfully requested for year:2015, county:005
Added 3666 rows
succesfully requested for year:2015, county:007
Added 5857 rows
succesfully requested for year:2015, county:009
Added 4417 rows
succesfully requested for year:2015, county:011
Added 3605 rows
succesfully requested for year:2015, county:013
Empty
succesfully requested for year:2015, county:015
Empty
succesfully requested for year:2015, county:017
Empty
succesfully requested for year:2015, county:019
Added 42744 rows
succesfully requested for year:2015, county:021
Added 2927 rows
succesfully requested for year:2015, county:023
Added 4318 rows
succesfully requested for year:2015, county:025
Added 24749 rows
succesfully requested for year:2015, county:027
Added 116854 rows
succesfully requested for year:2015, county:029
Added 38006 rows
succesfully requested for year:2015, county:031
Added 18226 rows
succesfully requested for year:2015, county:033
Added 25802 rows
succesfully requested for year:2015, county:035
Empty
succesfully requested for year:2015, county:037
Added 82131 rows
succesfully requested for year:2015, county:039
Added 17453 rows
succesfully requested for year:2015, county:041
Empty
succesfully requested for year:2015, county:043
Added 8692 rows
succesfully requested for year:2015, county:045
Empty
succesfully requested for year:2015, county:047
Added 8713 rows
succesfully requested for year:2015, county:049
Empty
succesfully requested for year:2015, county:051
Added 16895 rows
succesfully requested for year:2015, county:053
Added 26112 rows
succesfully requested for year:2015, county:055
Empty
succesfully requested for year:2015, county:057
Empty
succesfully requested for year:2015, county:059
Added 24852 rows
succesfully requested for year:2015, county:061
Empty
succesfully requested for year:2015, county:063
Empty
succesfully requested for year:2015, county:065
Added 98396 rows
succesfully requested for year:2015, county:067
Added 40453 rows
succesfully requested for year:2015, county:069
Added 17361 rows
succesfully requested for year:2015, county:071
Added 96956 rows
succesfully requested for year:2015, county:073
Added 73076 rows
succesfully requested for year:2015, county:075
Empty
succesfully requested for year:2015, county:077
Added 20352 rows
succesfully requested for year:2015, county:079
Added 49856 rows
succesfully requested for year:2015, county:081
Empty
succesfully requested for year:2015, county:083
Added 101901 rows
succesfully requested for year:2015, county:085
Added 8472 rows
succesfully requested for year:2015, county:087
Added 17317 rows
succesfully requested for year:2015, county:089
Added 8695 rows
succesfully requested for year:2015, county:091
Empty
succesfully requested for year:2015, county:093
Empty
succesfully requested for year:2015, county:095
Empty
succesfully requested for year:2015, county:097
Empty
succesfully requested for year:2015, county:099
Added 7872 rows
succesfully requested for year:2015, county:101
Added 2208 rows
succesfully requested for year:2015, county:103
Empty
succesfully requested for year:2015, county:105
Empty
succesfully requested for year:2015, county:107
Added 30395 rows
succesfully requested for year:2015, county:109
Empty
succesfully requested for year:2015, county:111
Added 52500 rows
succesfully requested for year:2015, county:113
Empty
succesfully requested for year:2015, county:115
Empty
1101829
[['2015', '001'], ['2015', '003'], ['2015', '013'], ['2015', '015'], ['2015', '017'], ['2015', '035'], ['2015', '041'], ['2015', '045'], ['2015', '049'], ['2015', '055'], ['2015', '057'], ['2015', '061'], ['2015', '063'], ['2015', '075'], ['2015', '081'], ['2015', '091'], ['2015', '093'], ['2015', '095'], ['2015', '097'], ['2015', '103'], ['2015', '105'], ['2015', '109'], ['2015', '113'], ['2015', '115']]

In [13]:
#These next few lines clean up the dataframe by adding a year column, months column, and county names
equiv = { "001": "Alameda", "003": "Apline", "005": "Amador", "007":"Butte", "009":"Calaveras", "011": "Colusa", "013":"Contra Costa", "015":"Del Norte", "017":"El Dorado", "019": "Fresno", "021": "Glenn", "023": "Humboldt", "025": "Imperial", "027": "Inyo", "029": "Kern", "031": "Kings", "033":"Lake", "035": "Lassen", "037": "Los Angeles", "039": "Madera", "041": "Marin", "043": "Mariposa", "045": "Mendicino", "047": "Merced", "049": "Modoc", "051": "Mono", "053": "Monterey", "055": "Napa", "057": "Nevada", "059": "Orange", "061": "Placer", "063": "Plumas", "065": "Riverside", "067": "Sacramento", "069": "San Benito", "071": "San Bernardino", "073": "San Diego", "075": "San Francisco", "077": "San Joaquin", "079": "San Luis Obispo", "081": "San Mateo", "083": "Santa Barbara", "085": "Santa Clara", "087": "Santa Cruz", "089": "Shasta", "091": "Sierra", "093": "Siskiyou", "095": "Solano", "097": "Sonoma", "099": "Stanislaus", "101": "Sutter", "103": "Tehama", "105": "Trinity", "107": "Tulare", "109": "Tuolumne", "111": "Ventura", "113": "Yolo", "115": "Yuba"}

#Show all the columns from the queried dataframe
print(master_df.columns)

#Only pick certain columns to a cleaned dataFrame
df_trim1 = master_df[['County Code','Date Local','24 Hour Local','Date GMT','Sample Measurement', "Sample Frequency",'Units of Measure','Sample Duration']]

#column for months
df_trim1['Date Local'] = pd.to_datetime(df_trim1['Date Local'])
df_trim1.drop(df_trim1.index[318396], inplace=True)
df_trim1['Month'] = pd.DatetimeIndex(df_trim1['Date Local']).month
df_trim1["Month"].fillna(0)
df_trim1["Month"].astype(float)
df_trim1.fillna(0)


#columns for years
df_trim1['Date Local'] = pd.to_datetime(df_trim1['Date Local'])
df_trim1.drop(df_trim1.index[318396], inplace=True)
df_trim1['Year'] = pd.DatetimeIndex(df_trim1['Date Local']).year
df_trim1["Year"].fillna(0)
df_trim1["Year"].astype(float)
df_trim1.fillna(0)

#column for county names
df_trim1["County Names"] = df_trim1["County Code"].map(equiv)
df_trim1.columns

#changes the types of sample measurements and County Names to float and string so they are manageble
df_trim1['Sample Measurement'] = df_trim1['Sample Measurement'].astype(float)
df_trim1['County Names'] = df_trim1['County Names'].astype(str)

#print the column types
print(df_trim1.columns)

Index(['Latitude', 'Longitude', 'Datum', 'Horizontal Accuracy', 'State Code',
       'County Code', 'Site Num', 'Parameter Code', 'POC',
       'AQS Parameter Desc', 'Date Local', '24 Hour Local', 'Date GMT',
       '24 Hour GMT', 'Year GMT', 'Day In Year GMT', 'Sample Measurement',
       'Units of Measure', 'Sample Duration', 'Sample Frequency',
       'Detection Limit', 'Measurement Uncertainty', 'Qualifier Description',
       'Method Type', 'Method Description'],
      dtype='object')

C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Index(['County Code', 'Date Local', '24 Hour Local', 'Date GMT',
       'Sample Measurement', 'Sample Frequency', 'Units of Measure',
       'Sample Duration', 'Month', 'Year', 'County Names'],
      dtype='object')

C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\shaheen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [14]:
#look at the first 5 rows of cleaned dataframe
df_trim1.head()

,County Code,Date Local,24 Hour Local,Date GMT,Sample Measurement,Sample Frequency,Units of Measure,Sample Duration,Month,Year,County Names
0,005,2015-09-07,23:00,2015-09-08,56.3,,Degrees Fahrenheit,1 HOUR,9.0,2015.0,Amador
1,005,2015-09-07,22:00,2015-09-08,58.6,,Degrees Fahrenheit,1 HOUR,9.0,2015.0,Amador
2,005,2015-09-07,00:00,2015-09-07,52.0,,Degrees Fahrenheit,1 HOUR,9.0,2015.0,Amador
3,005,2015-09-07,20:00,2015-09-08,66.0,,Degrees Fahrenheit,1 HOUR,9.0,2015.0,Amador
4,005,2015-09-07,19:00,2015-09-08,69.6,,Degrees Fahrenheit,1 HOUR,9.0,2015.0,Amador